apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmanager
  template:
    metadata:
      labels:
        app: dbmanager
    spec:
      hostAliases:
        - ip: "192.168.137.35"
          hostnames:
            - "api.famquest.nephele.ari-imet.eu"
            - "minio.famquest.nephele.ari-imet.eu"
            - "minioapi.famquest.nephele.ari-imet.eu"
            - "portal.famquest.nephele.ari-imet.eu"
            - "monitoring.famquest.nephele.ari-imet.eu"
      imagePullSecrets:
        - name: gatewaysecrets
        - name: guigomchasecrets
      containers:
      - name: dbmanager
        image: ghcr.io/guigomcha/famquest/dbmanager:latest
        ports:
        - containerPort: 8080
        command: ["/bin/sh"]
        args: ["-c", "./dbmanager"]
        env:
          - name: SWAGGER_URL
            value: "api.famquest.nephele.ari-imet.eu"
          - name: SWAGGER_SCHEMA
            value: "https"
          - name: SWAGGER_BASE_PATH
            value: ""
          - name: SWAGGER_PORT
            value: "8080"
          - name: MINIO_URL
            value: "minioapi.famquest.nephele.ari-imet.eu"
          - name: MINIO_USER
            value: "demo"
          - name: MINIO_PASSWORD
            value: "mypassword"
          - name: POSTGRES_DB_HOST
            value: "postgresql-svc"
          - name: POSTGRES_DB_PORT
            value: "5432"
          - name: POSTGRES_DB_USER
            value: "myuseradmin"
          - name: POSTGRES_DB_PASSWORD
            value: "mypassword"
---
apiVersion: v1
kind: Service
metadata:
  name: dbmanager-svc
spec:
  selector:
    app: dbmanager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
