apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontmanager
  template:
    metadata:
      labels:
        app: frontmanager
    spec:
      hostAliases:
        - ip: "192.168.137.35"
          hostnames:
            - "api.famquest.nephele.ari-imet.eu"
            - "portal.famquest.nephele.ari-imet.eu"
            - "monitoring.famquest.nephele.ari-imet.eu"
      imagePullSecrets:
        - name: gatewaysecrets
        - name: guigomchasecrets
      containers:
      - name: frontmanager
        image: ghcr.io/guigomcha/famquest/frontmanager:latest
        ports:
        - containerPort: 80
        env:
          - name: REACT_APP_API_URL
            value: "https://api.famquest.nephele.ari-imet.eu"
---
apiVersion: v1
kind: Service
metadata:
  name: frontmanager-svc
spec:
  selector:
    app: frontmanager
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
