# Configures the NGINX reverse proxy redirects 
proxy:
  routing: subdomain # location or subdomain
  services:
    - routingKey: portal
      dropRoutingKey: false
      svcName: frontmanager-svc
      namespace: REPLACE_TARGET_USER
      port: 8081
    - routingKey: api
      dropRoutingKey: false
      svcName: dbmanager-svc
      namespace: REPLACE_TARGET_USER
      port: 8080
  auth:
    enabled: true
    routingKey: auth
    svcName:  gateway-svc
    namespace: REPLACE_TARGET_USER
    port: 4180
    secretCookie: "REPLACE"
    realmUrl: https://keycloak.common.REPLACE_BASE_DOMAIN/realms/REPLACE_TARGET_USER 
    client: famquest-backend
    secret: "REPLACE"
  # Extra configurations for the reverse proxy (NGINX syntax)
  extraServerConfig:
    enabled: false
    extraServerHosts:  []
    content: ""

# Configures the K8s manifests
common:
  labels:
    # Useful to link to other deployments
    app: gateway
    fullapp: famquestREPLACE_TARGET_USER
  baseDomain: REPLACE_TARGET_USER.famquest.REPLACE_BASE_DOMAIN
  pullSecret: guigomchasecrets

# Configure the Exposure layer
ingress:
  tls: true
  email: REPLACE@gmail.com
  exporters: false # indirectly 
