{{- $common := .Values.common }}
{{- $ingress := .Values.ingress }}
{{- $auth := .Values.proxy.auth }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}-deployment
  labels:
    {{- with $common.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- with $common.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: 1
  template:
    metadata:
      labels:
      	{{- with $common.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: exporter-advanced
          image: ghcr.io/guigomcha/famquest/fluentd-nginx-exporter:develop
          ports: 
            - containerPort: 24231
          command:
            - fluentd
            - '-c'
            - /etc/fluentd/fluent.conf
          volumeMounts:
            - name: shared-nginx-logs
              mountPath: /var/log/nginx
            - name: nginx-log-fluentd-config
              mountPath: /etc/fluentd
        - name: exporter-basic
          image: nginx/nginx-prometheus-exporter:1.3.0
          ports:
            - containerPort: 9113
          args:
            - --nginx.scrape-uri=http://127.0.0.1:9000/stub_status
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 9000
          # args:
          #   - "--nginx-status=true"
          #   - "--nginx-status-port=9000"
          volumeMounts:
            - name: shared-nginx-logs
              mountPath: /var/log/nginx
            - name: nginx-config
              mountPath: /etc/nginx 
      {{- if $auth.enabled }}
        - name: oauth
          image: quay.io/oauth2-proxy/oauth2-proxy
          ports:
            - containerPort: {{ $auth.port }}
            - containerPort: 8080
            - containerPort: 44180
          args:
            - "--http-address=0.0.0.0:{{ $auth.port }}"
            - --metrics-address=0.0.0.0:44180
            - "--cookie-domain={{ $common.baseDomain }}"
            - "--whitelist-domain=*.{{ $common.baseDomain }}"
            - --oidc-issuer-url={{ $auth.realmUrl }}
            - --code-challenge-method=S256 
            - --insecure-oidc-allow-unverified-email
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: {{ $auth.secretCookie }}
            - name: OAUTH2_PROXY_CLIENT_ID
              value: {{ $auth.client }}
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: {{ $auth.secret }}
            - name: OAUTH2_PROXY_PROVIDER
              value: keycloak-oidc
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
            - name: OAUTH2_PROXY_REDIRECT_URL
            {{- if $ingress.tls }}
              value: "https://{{ $auth.routingKey }}.{{ $common.baseDomain }}/oauth2/callback"
            {{- else }}
              value: "http://{{ $auth.routingKey }}.{{ $common.baseDomain }}/oauth2/callback"
            {{- end }}
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: "0.0.0.0:{{ $auth.port }}"
            - name: OAUTH2_PROXY_COOKIE_DOMAINS
              value: {{ $common.baseDomain }}
            - name: OAUTH2_PROXY_SESSION_STORE_TYPE
              value: cookie
            - name: OAUTH2_PROXY_COOKIE_SAMESITE
              value: lax
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: "true"
            - name: OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST
              value: "false"
            - name: OAUTH2_PROXY_COOKIE_CSRF_EXPIRE
              value: 1m
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_PASS_USER_HEADERS
              value: "true"
            - name: OAUTH2_PROXY_SET_XAUTHREQUEST
              value: "true"   
      {{- end }}
      volumes:
        - name: shared-nginx-logs
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: {{ include "gateway.fullname" . }}-cm
            items:
              - key: services.conf
                path: conf.d/services.conf
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-log-fluentd-config
          configMap:
            name: {{ include "gateway.fullname" . }}-cm
            items:
              - key: fluent.conf
                path: fluent.conf
      imagePullSecrets:
        - name: {{ $common.pullSecret }}