# Configures the NGINX reverse proxy redirects 
proxy:
  routing: subdomain # location or subdomain
  services:
    - routingKey: portal
      dropRoutingKey: false
      svcName: frontmanager-svc
      namespace: famquest
      port: 8081
    - routingKey: pgadmin
      dropRoutingKey: false
      svcName: pgadmin-svc
      namespace: famquest
      port: 15432
    - routingKey: api
      dropRoutingKey: false
      svcName: dbmanager-svc
      namespace: famquest
      port: 8080
    - routingKey: minio
      dropRoutingKey: false
      svcName: minio-svc
      namespace: famquest
      port: 9001
  auth:
    enabled: false
    routingKey: auth
    svcName:  gateway-svc
    namespace: famquest
    port: 4180
    secretCookie: REPLACE
    realmUrl: https://keycloak.evidenresearch.eu/realms/bdsrdspain-sns 
    client: test
    secret: REPLACE
  # Extra configurations for the reverse proxy (NGINX syntax)
  extraServerConfig:
    enabled: true
    extraServerHosts:  # for the Ingress
      - routingKey: monitoring
    content: |
      server {
        listen 80;
        server_name monitoring.famquest.nephele.ari-imet.eu;
        resolver kube-dns.kube-system.svc.cluster.local valid=10s;
        location / {
          proxy_pass http://promstack-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090;
        }
      }


# Configures the K8s manifests
common:
  labels:
    # Useful to link to other deployments
    app: gateway
    fullapp: famquest
  baseDomain: famquest.nephele.ari-imet.eu
  pullSecret: gatewaysecrets

# Configure the Exposure layer
ingress:
  tls: true
  email: guillermo.gomezchavez@eviden.com
  exporters: false # indirectly 
