package main

import (
	"context"
	"fmt"
	"log"

	_ "github.com/lib/pq"

	"net/http"
	"os"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"

	// API demo https://www.soberkoder.com/swagger-go-api-swaggo/
	// Use https://github.com/swaggo/swag#declarative-comments-format to format REST API
	// pkg/api/docs folder is generated by Swag CLI, check readme.
	"famquest/components/db-manager/pkg/api"
	"famquest/components/db-manager/pkg/api/docs"
	"famquest/components/db-manager/pkg/connection"
	"famquest/components/db-manager/pkg/connection/memory"
	"famquest/components/db-manager/pkg/connection/postgresql"
	"famquest/components/db-manager/pkg/models"
	"famquest/components/go-common/logger"
)

func init() {
	// Env variables are used to inject the IP to the Host annotation to connect swagger correctly
	// even in prod
	host := os.Getenv("SWAGGER_URL")
	docs.SwaggerInfo.Host = host
	docs.SwaggerInfo.Schemes = []string{os.Getenv("SWAGGER_SCHEMA")}
	docs.SwaggerInfo.BasePath = os.Getenv("SWAGGER_BASE_PATH")
}

// userID, _ := ctx.Value("userID").(string)
func withUserID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		userID := r.Header.Get("X-User")
		// if values, ok := r.Header["X-User"]; ok && len(values) > 0 {
		// 	logger.Log.Debugf("User info in header: %+v\n", values)
		// 	userRef := values[0] // The value of the X-User header
		// 	dest, _, _ := crudGetAll(&models.Users{}, fmt.Sprintf("WHERE ext_ref = '%s'", userRef))
		// 	// Check if a user was found
		// 	if len(dest) == 0 {
		// 		logger.Log.Debugf("Should have found the user: %+v\n", dest)
		// 	} else {
		// 		if usr, ok := dest[0].(*models.Users); ok {
		// 			logger.Log.Debugf("User found: %+v\n", usr)
		// 			info["user"] = usr.ID
		// 		} else {
		// 			logger.Log.Debug("User not casted correctly")
		// 		}
		// 	}
		// }
		ctx := context.WithValue(r.Context(), "userID", userID)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// repo -> backend
// dto -> Data Transfer Object: adaptation between data systems with different data models (CRUD's create and update -> data model)

func getRouter() *mux.Router {

	var uh api.UserHandler
	var mh api.MediaHandler
	var ch api.CommentHandler
	var lh api.LocationHandler
	var th api.TripHandler
	var rh api.RelationHandler
	var ph api.PostHandler
	if usePostgres := os.Getenv("POSTGRES_DB_HOST") != ""; usePostgres {
		err := connection.ConnectToPostgreSQL()
		if err != nil {
			log.Fatalf("Unable to connect to DB %s", err.Error())
		}
		userRepo := postgresql.NewPostgresUser()
		uh = api.NewUserHandler(userRepo)
		mediaRepo := postgresql.NewPostgresMedia()
		mh = api.NewMediaHandler(mediaRepo)
		commentRepo := postgresql.NewPostgresComment()
		ch = api.NewCommentHandler(commentRepo)
		tripRepo := postgresql.NewPostgresTrip()
		th = api.NewTripHandler(tripRepo)
		locationRepo := postgresql.NewPostgresLocation()
		lh = api.NewLocationHandler(locationRepo)
		relationRepo := postgresql.NewPostgresRelation()
		rh = api.NewRelationHandler(relationRepo)
		postRepo := postgresql.NewPostgresPost()
		ph = api.NewPostHandler(postRepo)
	} else {
		userRepo := memory.NewMemoryCRUD[models.User]()
		uh = api.NewUserHandler(userRepo)
		mediaRepo := memory.NewMemoryCRUD[models.Media]()
		mh = api.NewMediaHandler(mediaRepo)
		commentRepo := memory.NewMemoryCRUD[models.Comment]()
		ch = api.NewCommentHandler(commentRepo)
		tripRepo := memory.NewMemoryCRUD[models.Trip]()
		th = api.NewTripHandler(tripRepo)
		locationRepo := memory.NewMemoryCRUD[models.Location]()
		lh = api.NewLocationHandler(locationRepo)
		relationRepo := memory.NewMemoryCRUD[models.Relation]()
		rh = api.NewRelationHandler(relationRepo)
		postRepo := memory.NewMemoryCRUD[models.Post]()
		ph = api.NewPostHandler(postRepo)
	}

	r := mux.NewRouter()
	r.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	r.HandleFunc("/health", api.Health).Methods("GET", "OPTIONS")
	r.HandleFunc("/configure", api.Configure).Methods("GET", "OPTIONS")

	r.HandleFunc("/users", uh.ListUsers).Methods("GET")
	r.HandleFunc("/users", uh.CreateUser).Methods("POST")
	r.HandleFunc("/users/{id}", uh.GetUser).Methods("GET")
	r.HandleFunc("/users/{id}", uh.UpdateUser).Methods("PUT")
	r.HandleFunc("/users/{id}", uh.DeleteUser).Methods("DELETE")

	r.HandleFunc("/media", mh.UploadMedia).Methods("POST")
	r.HandleFunc("/media", mh.ListMedia).Methods("GET")
	r.HandleFunc("/media/{id}", mh.GetMedia).Methods("GET")
	r.HandleFunc("/media/{id}", mh.UpdateMedia).Methods("PUT")
	r.HandleFunc("/media/{id}", mh.DeleteMedia).Methods("DELETE")

	r.HandleFunc("/comments", ch.CreateComment).Methods("POST")
	r.HandleFunc("/comments", ch.ListComments).Methods("GET")
	r.HandleFunc("/comments/{id}", ch.GetComment).Methods("GET")
	r.HandleFunc("/comments/{id}", ch.UpdateComment).Methods("PUT")
	r.HandleFunc("/comments/{id}", ch.DeleteComment).Methods("DELETE")

	r.HandleFunc("/trips", th.ListTrips).Methods("GET")
	r.HandleFunc("/trips", th.CreateTrip).Methods("POST")
	r.HandleFunc("/trips/{id}", th.GetTrip).Methods("GET")
	r.HandleFunc("/trips/{id}", th.UpdateTrip).Methods("PUT")
	r.HandleFunc("/trips/{id}", th.DeleteTrip).Methods("DELETE")

	r.HandleFunc("/locations", lh.ListLocations).Methods("GET")
	r.HandleFunc("/locations", lh.CreateLocation).Methods("POST")
	r.HandleFunc("/locations/{id}", lh.GetLocation).Methods("GET")
	r.HandleFunc("/locations/{id}", lh.UpdateLocation).Methods("PUT")
	r.HandleFunc("/locations/{id}", lh.DeleteLocation).Methods("DELETE")

	r.HandleFunc("/relations", rh.ListRelations).Methods("GET")
	r.HandleFunc("/relations", rh.CreateRelation).Methods("POST")
	r.HandleFunc("/relations/{id}", rh.GetRelation).Methods("GET")
	r.HandleFunc("/relations/{id}", rh.UpdateRelation).Methods("PUT")
	r.HandleFunc("/relations/{id}", rh.DeleteRelation).Methods("DELETE")

	r.HandleFunc("/posts", ph.ListPosts).Methods("GET")
	r.HandleFunc("/posts", ph.CreatePost).Methods("POST")
	r.HandleFunc("/posts/{id}", ph.GetPost).Methods("GET")
	r.HandleFunc("/posts/{id}", ph.UpdatePost).Methods("PUT")
	r.HandleFunc("/posts/{id}", ph.DeletePost).Methods("DELETE")
	return r

}

// @title FamQuest DB Manager API
// @version 0.4.0
// @description Handles the connection to the DBs in DB Manager. PostgreSQL and MINIO
// @termsOfService http://swagger.io/terms/
// @contact.name Guillermo Gomez
// @contact.url https://github.com/guigomcha/famquest/
// @contact.email guillermo.gc1994@gmail.com
// @license.name Guillermo Gomez GPL V3
func main() {
	r := getRouter()

	// Start the server
	port := os.Getenv("SWAGGER_PORT")
	if port == "" {
		port = "8080" // Default port if not set
	}
	fmt.Printf("Starting server on port %s...\n", port)
	// Use CORS middleware to allow requests from frontend
	allowedOrigins := []string{
		"http://localhost:3000",
		"http://localhost:8081",
		"http://localhost:8080",
		"https://portal.staging.famquest.guigomcha.dynv6.net",
	}
	allowedMethods := []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
	allowedHeaders := []string{"Content-Type", "Accept"}
	logger.Log.Debugf("CORS: %+v, %+v, %+v", allowedOrigins, allowedHeaders, allowedMethods)

	if err := http.ListenAndServe(fmt.Sprintf(":%s", port), handlers.CORS(handlers.AllowedOrigins(allowedOrigins), handlers.AllowedMethods(allowedMethods), handlers.AllowedHeaders(allowedHeaders))(r)); err != nil {
		if usePostgres := os.Getenv("POSTGRES_DB_HOST") != ""; usePostgres {
			connection.DB.Close()
		}
		log.Fatal(err.Error())
	}
}
