# This docker-compose file can be used to bring up an example instance of oauth2-proxy
# for manual testing and exploration of features.
# Alongside OAuth2-Proxy, this file also starts Dex to act as the identity provider,
# etcd for storage for Dex, nginx as a reverse proxy and other http services for upstreams
#
# This file is an extension of the main compose file and must be used with it
#    docker-compose -f docker-compose.yaml -f docker-compose-nginx.yaml <command>
# Alternatively:
#    make nginx-<command> (eg make nginx-up, make nginx-down)
#
# Access one of the following URLs to initiate a login flow:
#    - http://oauth2-proxy.localtest.me
#    - http://pgadmin.oauth2-proxy.localtest.me  user=admin@example.com, password=password
#
# The OAuth2 Proxy itself is hosted at http://oauth2-proxy.oauth2-proxy.localtest.me
#
# Note, the above URLs should work with Chrome, but you may need to add hosts
# entries for other browsers
#    127.0.0.1 oauth2-proxy.localtest.me
#    127.0.0.1 httpbin.oauth2-proxy.localtest.me
#    127.0.0.1 oauth2-proxy.oauth2-proxy.localtest.me
#    127.0.0.1 keycloak.oauth2-proxy.localtest.me
version: '3.0'
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    ports: []
    hostname: oauth2-proxy
    container_name: oauth2-proxy
    command: --config /oauth2-proxy.cfg
    volumes:
      - "./oauth/oauth.cfg:/oauth2-proxy.cfg"
    networks:
      oauth2-proxy: {}
      httpbin: {}
      keycloak: {}
      databases: {}
    depends_on:
      - httpbin
      - keycloak
  nginx:
    depends_on:
      - oauth2-proxy
    container_name: nginx
    image: nginx:1.27
    restart: unless-stopped
    ports:
      - 80:80/tcp
    hostname: nginx
    volumes:
      - "./nginx/service.conf:/etc/nginx/conf.d/default.conf"
    networks:
      oauth2-proxy: {}
      httpbin: {}
      keycloak: {}
      databases: {}

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0
    hostname: keycloak
    command:
      - 'start-dev'
      - '--http-port=9080'
      - '--import-realm'
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: admin@example.com
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 9080:9080/tcp
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me
  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - 8080:80/tcp
    networks:
      httpbin:
        aliases:
          - httpbin.localtest.me
networks:
  httpbin: {}
  oauth2-proxy: {}
  keycloak: {}
  databases:
    name: databases
    external: true