version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: famquest
      POSTGRES_USER: myuseradmin
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U myuseradmin -d famquest'"] # User, Database
      interval: 5s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"  # Port for PostgreSQL database
    networks:
      databases:
        aliases:
          - postgresql.localtest.me

  pgadmin_domain: 
    image: dpage/pgadmin4:8.13
    container_name: pgadmin_famquest
    environment:
      PGADMIN_DEFAULT_EMAIL: myuseradmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypassword 
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./deploy/local/postgres/pgadmin.json:/pgadmin4/servers.json
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:80"  # Port for pgAdmin web UI
    networks:
      databases:
        aliases:
          - pgadmin.localtest.me
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    environment:
      MINIO_ROOT_USER: myuseradmin
      MINIO_ROOT_PASSWORD: mypassword
      MINIO_API_PORT_NUMBER: 5430  
      MINIO_CONSOLE_PORT_NUMBER: 5431 
    ports: # For some reason 9000 is busy in my PC
      - "5430:5430"  # Minio API port
      - "5431:5431"  # Minio console port
    volumes:
      - minio_data:/data  # Mount a volume for persistent data
    networks:
      databases:
        aliases:
          - minio.localtest.me
networks:
  databases: 
    name: databases

# Persistent volume for DBs
volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local
