version: '3.8'

services:
  pgadmin_domain:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_domain
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON: |
        [
          {
            "Name": "Famquest DB",
            "Group": "Servers",
            "Host": "famquest",
            "Port": 5432,
            "Username": "myuser",
            "SSLMode": "prefer"
          }
        ]
    ports:
      - 15432:80

  famquest:
    image: postgres:latest
    container_name: famquest
    environment:
      POSTGRES_DB: famquest
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  