version: '3.8'

services:
  pgadmin_domain:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_famquest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON: |
        [
          {
            "Name": "Famquest DB",
            "Group": "Servers",
            "Host": "famquest",
            "Port": 5432,
            "Username": "myuser",
            "SSLMode": "prefer"
          }
        ]
    ports:
      - 15432:80
  famquest:
    image: postgres:latest
    container_name: famquest
    environment:
      POSTGRES_DB: famquest
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    ports: # 9000 for some reason busy in localhost
      - 5430:5430
      - 5431:5431
    # volumes:
    #   - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=myuser
      - MINIO_ROOT_PASSWORD=mypassword
      - MINIO_API_PORT_NUMBER=5430
      - MINIO_CONSOLE_PORT_NUMBER=5431
      - MINIO_APACHE_API_HTTP_PORT_NUMBER=5430
      # - MINIO_DEFAULT_BUCKETS=image

# volumes:
#   minio_data:
#     driver: local  

C:\Users\a809921\.android