version: '3.8'

services:
  pgadmin_domain:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_famquest
    environment:
      PGADMIN_DEFAULT_EMAIL: $REPLACE_MYUSER@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: $REPLACE_MYPASSWORD
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON: |
        [
          {
            "Name": "Famquest DB",
            "Group": "Servers",
            "Host": "famquest_db",
            "Port": 5432,
            "Username": "$REPLACE_MYUSER",
            "SSLMode": "prefer"
          }
        ]
    ports:
      - "15432:80"  # Port for pgAdmin web UI

  famquest_db:
    image: postgres:latest
    container_name: famquest_db
    environment:
      POSTGRES_DB: famquest
      POSTGRES_USER: $REPLACE_MYUSER
      POSTGRES_PASSWORD: $REPLACE_MYPASSWORD
    ports:
      - "5432:5432"  # Port for PostgreSQL database

  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    environment:
      MINIO_ROOT_USER: $REPLACE_MYUSER
      MINIO_ROOT_PASSWORD: $REPLACE_MYPASSWORD
      MINIO_API_PORT_NUMBER: 5430  
      MINIO_CONSOLE_PORT_NUMBER: 5431 
    ports: # For some reason 9000 is busy in my PC
      - "5430:5430"  # Minio API port
      - "5431:5431"  # Minio console port
    volumes:
      - minio_data:/data  # Mount a volume for persistent data

  dbmanager:
    # image: ghcr.io/guigomcha/famquest/dbmanager:latest
    container_name: dbmanager
    environment:
      MINIO_URL: minio:5430
      MINIO_USER: $REPLACE_MYUSER
      MINIO_PASSWORD: $REPLACE_MYPASSWORD
    build:
      context: ../../
      dockerfile: components/db-manager/install/Dockerfile
      target: builder
      args:
        DEV: "True"
    ports:
      - "8080:8080"  # Port for dbmanager web UI
    volumes:
      - ../../components:/go/src/famquest/components
    command: sleep infinity
    working_dir: /go/src/famquest/components/db-manager
    depends_on:
      - minio
      - famquest_db

  frontend:
    # image: ghcr.io/guigomcha/famquest/frontmanager:latest
    build:
      context: ../../
      dockerfile: components/front-manager/install/Dockerfile
      target: builder
    container_name: frontend
    ports:
      - "8081:8081"
    volumes:
      - ../../components:/usr/src/famquest/components
    command: sleep infinity
    working_dir:  /usr/src/famquest/components/front-manager
    depends_on:
      - dbmanager

volumes:
  minio_data:
    driver: local  # Persistent volume for Minio data
