version: '3.8'

services:

  dbmanager:
    # image: ghcr.io/guigomcha/famquest/dbmanager:latest
    container_name: dbmanager
    environment:
      MINIO_URL: minio:5430
      MINIO_USER: myuseradmin
      MINIO_PASSWORD: mypassword
    build:
      context: ../../
      dockerfile: components/db-manager/install/Dockerfile
      target: builder
      args:
        DEV: "True"
    ports:
      - "8080:8080"  # Port for dbmanager web UI
    volumes:
      - ../../components:/go/src/famquest/components
    command: sleep infinity
    working_dir: /go/src/famquest/components/db-manager
    networks:
      databases:
        aliases:
          - api.localtest.me

  frontend:
    # image: ghcr.io/guigomcha/famquest/frontmanager:latest
    build:
      context: ../../
      dockerfile: components/front-manager/install/Dockerfile
      target: builder
    container_name: frontend
    ports:
      - "8081:8081"
    volumes:
      - ../../components:/usr/src/famquest/components
    command: sleep infinity
    working_dir:  /usr/src/famquest/components/front-manager
    depends_on:
      - dbmanager
    networks:
      databases:
        aliases:
          - portal.localtest.me

networks:
  databases:
    name: databases
    external: true

# volumes:
#   minio_data:
#     driver: local  # Persistent volume for Minio data
