apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: [ "sleep", "infinity" ]
    volumeMounts:
    - name: pvc-volume
      mountPath: /backups
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: backupmanager-pvc
