apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:6.15
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "REPLACE_USER@pgadmin.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "REPLACE_PASSWORD"
          - name: PGADMIN_LISTEN_PORT
            value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 15432
      targetPort: 80
  type: ClusterIP
