apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        envFrom:
          - secretRef:
              name: postgres-credentials
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresql-vol
      volumes:
      - name: postgresql-vol
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete (only when the pvc is deleted, not the pod)
  storageClassName: local-path
  resources:
    # The capacity limit will be ignored for now. https://github.com/rancher/local-path-provisioner/blob/master/README.md#cons
    requests: # Only for users
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: REPLACE_USER
  POSTGRES_PASSWORD: REPLACE_PASSWORD
  POSTGRES_DB: keycloak
  PGDATA: /var/lib/postgresql/data/k8s