# Configures the NGINX reverse proxy redirects 
proxy:
  routing: subdomain # location or subdomain
  services:
    - routingKey: pgadmin
      dropRoutingKey: false
      svcName: pgadmin-svc
      namespace: common
      port: 15432
    - routingKey: keycloak
      dropRoutingKey: false
      svcName: keycloak-svc
      namespace: common
      port: 8080
  auth: # This is the auth to provide a keycloak for the rest of the testbed
    enabled: false
    routingKey: empty
    svcName:  empty
    namespace: empty
    port: 8080
    secretCookie: "empty"
    realmUrl: empty
    client: empty
    secret: "empty"
  # Extra configurations for the reverse proxy (NGINX syntax)
  extraServerConfig:
    enabled: true
    extraServerHosts:  # for the Ingress
      - routingKey: prometheus
      - routingKey: grafana
    content: |
      server {
        listen 80;
        server_name prometheus.common.REPLACE_BASE_DOMAIN;
        resolver kube-dns.kube-system.svc.cluster.local valid=10s;
        location / {
          proxy_pass http://promstack-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090;
        }
      }
      server {
        listen 80;
        server_name grafana.common.REPLACE_BASE_DOMAIN;
        resolver kube-dns.kube-system.svc.cluster.local valid=10s;
        location / {
          proxy_pass http://promstack-grafana.monitoring.svc.cluster.local:80;
        }
      }


# Configures the K8s manifests
common:
  labels:
    # Useful to link to other deployments
    app: common
    fullapp: testbed
  baseDomain: REPLACE_BASE_DOMAIN
  pullSecret: guigomchasecrets

# Configure the Exposure layer
ingress:
  tls: true
  email: guillermo.gc1994@gmail.com
  exporters: false # indirectly 
