# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY famquest-ui/package*.json ./
RUN npm install

# Copy the rest of the app
COPY famquest-ui/ .

# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
