name: backupmanager

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'components/backup-manager/**'
      - '.github/workflows/backupmanager.yaml'
  pull_request:
    paths:
      - 'components/backup-manager/**'
      - '.github/workflows/backupmanager.yaml'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: guigomcha
          password: ${{ secrets.REGISTRY_PAT }}
      # Tests done in the dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: components/backup-manager/install/Dockerfile
          push: true
          tags: ghcr.io/guigomcha/famquest/backupmanager:latest
