name: dbmanager

on:
  push:
    branches:
      - main
      - develop
  pull_request:


jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: guigomcha
          password: ${{ secrets.REGISTRY_PAT }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: components/db-manager/install/Dockerfile
          push: true
          tags: ghcr.io/guigomcha/famquest/dbmanager:latest
